using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._White.UserInterface.Systems.CombatMode.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CombatModeGui : UIWidget
{
    private static readonly SpriteSpecifier FlashSprite = new SpriteSpecifier.Rsi(new ("/Textures/_White/Interface/Misc/screen_gen.rsi"), "flash");

    public CombatModeGui()
    {
        RobustXamlLoader.Load(this);
        var controller = UserInterfaceManager.GetUIController<CombatModeUIController>();

        CombatModeButton.OnToggled += _ => controller.ToggleCombatMode();

        CombatModeFlash.SetFromSpriteSpecifier(FlashSprite);
        CombatModeFlash.DisplayRect.TextureScale = new (2, 2);

        // Ensure the icon is visible before the first state update arrives
        OnCombatModeUpdated(false);
    }

    public void OnCombatModeUpdated(bool inCombatMode)
    {
        CombatModeButton.TexturePath = inCombatMode ? "/Textures/Interface/Actions/harm.png" : "/Textures/Interface/Actions/harmOff.png";
        CombatModeFlash.Visible = inCombatMode;
        CombatModeButton.SetClickPressed(inCombatMode);
    }

    public void SetCombatEnabled(bool enabled)
    {
        Visible = enabled;
        CombatModeButton.Disabled = !enabled;
        if (!enabled)
            CombatModeFlash.Visible = false;
    }
}
