contractor-background-job-blocked = Background requirements not met: {$backgrounds}
contractor-background-type-citizenship = Citizenship
contractor-background-type-planet = Planet
contractor-background-type-background = Background

background_name_concord-service = Concord Gardens Service
background_description_concord-service = Your routine was scripted: wake on signal, identical breakfast, practice smiles and bows in the mirror. A windowless berth, a locker with issued uniforms, an hour in VR before sleep, stimulants to keep the smile. Each cycle brought a medical checkup: scanners, tests, sleep and dosage control to keep the body working and the strain unseen. Staff lived in blocks: shared laundry, shared showers, brief chats in the supply room before the signal returned.
    By day you escorted the rich along the paths, curating a perfect picture, matching blankets to suits, carrying trays without a shake, reading who wanted attention and who wanted you gone. At night the garden closed and cleaning began: champagne traces on marble, smells in air handlers, swapping scent cartridges. If an accident happened, you sealed the area, removed the body, hid the signs. Morning meant the same smile and no word about the night.

background_name_underground-medtech = Undercity Medtech
background_description_underground-medtech = Beneath Eden's postcard lay the Undercity: cramped blocks, recirculated air, peeling neon, fans instead of quiet. Life ran on queues and debts: rations, water, salvaged filters, traded favors. Upper terraces were barely mentioned: some reassigned, some written off and taken away so no extra questions reached the showcase.
    The clinic saw almost no funding: everything official went upstairs, leaving spent cassettes and empty kits below. Your shift started by checking the resuscitator powers on, that there are any fluids and bandages, then triage—from fertilizer burns and job cuts to asphyxiation in clogged drains and dirty-water complications. Painkillers came in tiny doses, IVs were built from leftovers, tools bought on the black market, and paper records hidden so inspectors couldn't shut the room with one order.

background_name_odd-job = Odd Job Worker
background_description_odd-job = In the Undercity your life was a cramped block, recirculated air, rationed water, and a queue even for the shower. Above: resort lights and hall music; below: fans, damp, and talk of those written off. Rations and filters were split, sleep broke on alarms and leaks. Personal belongings were minimal: a work jacket, a few tools, debts growing faster than the days.
    Work was whatever others refused: clear a clogged drain, haul waste, patch a leak, strip a broken unit for parts, scrub out accident traces. Pay came as food, filters, a charging slot, cash via a middleman, or just a promise not to report you. If you had to go topside, you got someone else's pass for a short window and had to vanish before inspections so extra faces didn't surface.

background_name_elite-dock-guard = Elite Dock Security
background_description_elite-dock-guard = The elite dock was a world inside Eden: filtered air, soft light, carpeted quiet, and routes tailored to guests. Security lived nearby in a service block: your own bunk and gear locker, regulated meals, and a clinic that worked fast without questions. Every day started with readiness checks: headset charged, clearances updated, uniform spotless, reactions steady.
    You controlled entries and flow: checked passes and faces, blocked strays, and escorted violators out via service lifts without arguments. Servants were managed separately: where to vanish, where to stand, how close to approach guests. Any attempt to remove extras, linger near conversations, or disrupt order was shut down hard; the dock had to remain calm and beautiful.

background_name_ring-dock-loader = Ring Dock Loader
background_description_ring-dock-loader = The ring docks ran around the clock: metal smell, cold warehouse air, bunks beside the outflow point, uniform dryers, a ration canteen, and a clinic checking backs and joints. Your pass hung on your neck—without it no gates, no lockers. Cameras watched like the docks were shy of their own workers. Borgs moved the same corridors, quiet and numbered; charging bays smelled of ozone and smoke breaks were full of grumbling about how fast life shifts and who still belongs.
    The job was flow: scan, seal, strops, tie-downs, a tick in the manifest. If a tag mismatched or the weight drifted, you halted the section and called a lead. Borgs handled the smooth routine; you got everything that could spark a dispute and needed a human signature. Mistakes weren’t shouted about—logged instead, and after a couple entries someone could lose clearance without explanation. Management liked it that way: cargo moves and nobody argues.

background_name_hydroponics-worker = Hydroponics Worker
background_description_hydroponics-worker = In the Blooming Gardens the air was wet and clothes smelled of greens. You lived beside the greenhouses, each with a private room for crates, tools, and personal stuff. It was quiet: only ventilation and the distant drone of pumps. Borgs rolled past with containers more and more each cycle, while your human coworkers grew fewer.
    Your work: filters, sprayers, concentrate, and test strips to check solution, plus scraping mold when sensors pinged. Borgs did the routine, but faults and decisions stayed on you—and so did the responsibility. You took the plots where readings diverged and had to find the cause before the plants suffered. If a borg locked up and called an engineer, you closed the plot manually so the greenhouse didn’t stall. Reports made it look like the human once again backed up the machine.

background_name_spire-climate-engineer = Spire Climate Engineer
background_description_spire-climate-engineer = The Council Spire sat above the fields like its own city: dry air, even light, silence behind double doors. Engineers had separate rooms and a proper cafeteria, but passes were checked on every crossing. Borgs walked the service halls, numbered and mute, and people stepped aside automatically. Down below they were hated; above they were called savings and safety. You lived between those words and didn’t ask extra questions.
    You handled comms, power, and climate: server racks, backup batteries, pumps, temperature and humidity sensors. You were called for overheating, leaks, and power drops, and every decision carried your signature. At the same time you serviced the borgs: calibrated manipulators, cleaned connectors, checked their sensors. People sabotaged them just enough to make a borg stop and call an engineer, and you brought the system back to normal while the cameras recorded only the end result.

background_name_production-manager = Production Manager
background_description_production-manager = You didn’t live on the line but beside it: an office above the shop floor, a screen and radio on the desk. Conditions beat the crews’, but the phone rang more and every day started with numbers and surnames. In the documents people were a list; borgs had their own line as equipment—number, charge, access zone. Leadership loved them for predictability: they don’t get sick or argue, and their reports stay flat. Down below people grumbled that every new borg meant someone’s hours gone.
    You received harvests from co-ops, set what got processed first, and pushed shipping to quota. If a conveyor failed or a container was late, you had to reshuffle the queue, find reserves, and call repairs before the warehouse clogged. People were moved like parts because time here cost more than words. Borgs covered the heavy, monotonous segments so the line didn’t stop; you kept the signatures and decisions. And the more borgs arrived, the more often people looked for a human name to pin a failure on instead of fixing the root cause.

background_name_nt-inspector = NT Inspector
background_description_nt-inspector = You arrived on Delta as an NT inspector and lived apart from locals: a service block, security, ration meals. Smiles faded as soon as you showed credentials. Distance was mandatory—friendship too easily became a request to look away. Routes ran through fields and warehouses; the planet looked calm for how much money moved through its docks. Workdays started with a point list and ended late—not from heavy lifting, but from double-checking details and leaving no dark corners.
    The audit was straightforward: match cargo to paperwork and find where the extra vanished. You checked seals and markings, pulled readings from scales, traced batch records, and compared them to the stock on hand. If something didn’t line up, shipment halted, the section was sealed, and local security escorted you. You had enough authority to delay a flight and collect statements, even if it ruined someone’s season.

background_name_parts-factory-engineer = Parts Factory Engineer
background_description_parts-factory-engineer = Engineers lived in a barracks by the factory: shared kitchen, showers with filters you cleaned more often than you liked, and the constant hum of conveyors through the wall. Windows looked onto docks and loading tracks where shifts never ended. Mornings meant meal tickets from the canteen; evenings meant the parts market—filters and masks swapped for batteries and food. Neighbors pulled usable pieces from scrapped gear and lent tools for help during inspections or awkward shifts. At night you listened for pressure in the pipes and kept a bag of consumables and passes by the door: miss a call and your name vanished from the roster.
    Everything followed the rulebook. Line, shifts, and people lived by timers, and any deviation was logged. Engineers serviced machines strictly by instruction, with stamps and signatures under constant oversight. Decisions outside procedure counted as violations, even if they avoided a fault. Stopping a line had to be proven in numbers; keeping it running had to be justified by metrics. Nobody asked why something failed—only whether you stayed within tolerance. A shift was done if the log matched, indicators stayed green, and smoke breaks didn’t exceed the permitted count.

background_name_police-officer = Police Officer
background_description_police-officer = Patrols were housed wherever space remained: under station roofs, in dock barracks, beside districts that never slept. Rooms were cramped, light was dim, and windows stared at routes lit by neon even at night. Days began with bulletins and cold coffee; nights with calls that never made it fully into reports. Shift schedules collapsed around incoming flights, and free time dissolved between waiting and another trip to where something went wrong.
    On duty, the law was a shadow between contracts. Murders in service corridors were written off as accidents; disappearances in housing drowned in paperwork; dock raids collapsed if the cargo bore a corporate flag. Corporations held their blocks shut: own security, lawyers on speed dial, cameras police couldn’t access. Work was done at the edges—pulling people who stepped outside the perimeter, extracting witnesses before someone else did, building chains of hints instead of direct evidence. A good shift meant the case was closed, noise was muted, and the city held together for one more night.

background_name_clinic-doctor = Clinic Doctor
background_description_clinic-doctor = Doctors got communal housing—service rooms or bunks in a nearby block. Space was tight, light even and bland, climate strictly by the book with no surprises. The kitchen was shared and tasted the same at any hour; evenings meant quick chats before everyone scattered back to their rooms. Living beside the clinic mattered not for comfort but because the surrounding infrastructure almost never failed and needed little attention.
    The patient flow never stopped, but not everyone was treated equally. Corporate insurance opened doors and access to meds; others waited for a slot and spare supplies. Miners, loaders, techs came in with burns, cuts, dust-wrecked lungs, and fatigue no diagnosis covered. Machines were old but kept their modes if filters and cassettes were swapped on time. At shift’s end the logs were closed carefully: the report had to line up even if the care didn’t.

background_name_dome-dispatcher = Dome Dispatcher
background_description_dome-dispatcher = Dispatchers lived in separate sections near the dome center, where the city looked calmer than it was. Lights failed less, climate and comms held steadier, and household glitches were fixed before anyone spoke out loud. Rooms were small but shielded from noise; transit and services ran on schedule, just like the regulations promised. Evenings were spent in the mess or lounges, trading dome news, rumors of coming reworks, and which corporations were bending routes again. Free time let you sleep between shifts, but the feeling of being on call never left.
    On the console the feeds merged: evacuations, tunnel closures, repair team requests. Dispatchers cut the signal noise, sorting real threats from corporate chatter, and rerouted movement so the dome wouldn’t stall. Corporations constantly pushed at the timetables—demanding priority, closing sectors “for maintenance,” forcing their windows as urgent work. Officially everything followed protocol; in practice, deals decided plenty. The dome layout changed fast, and dispatchers memorized it before the maps updated. The job boiled down to balance the system before corporate interests tore the dome into pieces that suited them.

background_name_utility-worker = Utility Worker
background_description_utility-worker = Life played out in standard sector blocks with shared kitchens and laundry on schedule, in buildings of long stairwells and dark landings where someone always lingered to talk or just stand in the shadows. It was crowded and noisy but familiar: neighbors knew each other, traded rumors, complaints, and quiet warnings, discussed outages, repairs, and which entrances to avoid. Evenings meant crowded kitchens, rotating laundry, and doors shut tighter than usual. Life ran on habit, not rules.
    Work was simple and physical: sweeping stairwells, hauling trash, cleaning corridors, and restoring common areas that fell into disorder fast. Complaints came non-stop: dirt, smell, noise, traces of night fights. Often you cleaned before police arrived and avoided questions. Local gangs kept a silent pact: leave utilities alone, and they don’t linger where they shouldn’t. Every exit was logged so you could pass checkpoints and dodge raids. The goal was simple: make the building look calm even if it hadn’t been inside for a long time.
