# character-employer-requirement = You must{$inverted ->
#     [true]{" "}not
#     *[other]{""}
# } be employed by one of these: {$employers}

employer_name_alpha-centauri-ab = Alpha Centauri A b
employer_description_alpha-centauri-ab = Alpha Centauri A b is the first extrasolar colony and capital of the Federation, hosting parliament sessions. The planet is terraformed; cities are built in access layers from docks and services up to research campuses and offices. Routes are certified here, equipment is approved, and standards are issued for the outer worlds to follow. Bluespace makes comms costly and laggy, so critical decisions travel by courier.
    Alpha's culture mixes showcase opulence with nostalgia for old Earth: upper sectors run museum seasons and vintage cinema, dressing sets in Earth eras. Every few years they celebrate a new GS and a week of parliamentary sessions—streets close, broadcasts run, receptions and awards fill the schedule. A special draw is rare open broadcasts from Earth; speech and fashion get calibrated against them, even when dates jump decades, once delivering congratulations from 2225. Below, life is simpler: markets, public cinemas, and quick service festivals praising those who never make the reports.
    In 25 GS Alpha opened a route to Earth and folded it into the Federation as a protected autonomous subject without authority over colonies. Alpha's politics hinge on two forces: the Federation sets rules and can halt projects with a single decision, while corporations bargain for exceptions through contracts and infrastructure. Earth's protected status is a bargaining chip in access and priority talks because behind the wording lie budgets and reputation. Lobbying swirls around quotas, routes, and funding for comms and science—the best phrasing wins, not the loudest slogan.
