using Content.Shared._Invicta.Economy.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Robust.Client.UserInterface;
using Robust.Shared.Prototypes;
using Content.Shared.Roles;

namespace Content.Client._Invicta.Economy.Bank.UI.ManagementConsole.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccountManagementTab : Control
{
    [Dependency] private readonly EntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly List<AccountEntry> _accounts = new();
    private readonly List<string> _jobs = new();
    private static readonly ProtoId<JobPrototype> DefaultJobPrototype = "Passenger";
    private static readonly int[] DefaultSalaryButtons = { -10, -1, 1, 10 };
    private ProtoId<JobPrototype> _defaultJob = DefaultJobPrototype;
    private string? _currentAccountId;
    private EconomyBankAccountSystemShared _bankAccountSystem = default!;
    private string _defaultJobName = string.Empty;
    private int _defaultJobIndex = -1;
    private EconomyBankAccountMask _accountMask = EconomyBankAccountMask.All;
    private List<BankAccountTag>? _accountTags;
    private bool _allowCentralAccounts;
    private bool _allowRestrictedAccounts;

    public Action<string, bool>? OnBlockAccountPressed;
    public Action<string, string>? OnChangeNamePressed;
    public Action<string, string>? OnChangeJob;
    public Action<string, ulong>? OnChangeSalary;

    public bool Priveleged;

    public AccountManagementTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _bankAccountSystem = _entityManager.System<EconomyBankAccountSystemShared>();
        SetDefaultJob(null);

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>().ToList();
        jobs.Sort((x, y) => string.Compare(x.LocalizedName, y.LocalizedName, StringComparison.CurrentCulture));
        foreach (var job in jobs)
        {
            if (!job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                continue;

            _jobs.Add(job.ID);
            JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobs.Count - 1);
        }

        UpdateDefaultJobIndex();
        ConfigureSalaryButtons(null);

        UpdateAccountList();

        FindAccount.OnTextEntered += OnTextEnteredAccount;
        SalaryAmountBox.ValueChanged += OnSalaryValueChanged;

        BlockButton.OnPressed += _ =>
        {
            if (_currentAccountId is null)
                return;

            var blocked = TryGetCurrentAccount(out var account) && account.Blocked;
            OnBlockAccountPressed?.Invoke(_currentAccountId, !blocked);
        };
        ChangeNameButton.OnPressed += _ =>
        {
            if (_currentAccountId is null || ChangeNameBox.Text.Length <= 0)
                return;

            OnChangeNamePressed?.Invoke(_currentAccountId, ChangeNameBox.Text);
            ChangeNameBox.Clear();
        };
        JobPresetOptionButton.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);

            var bankAccountSystem = _entityManager.System<EconomyBankAccountSystemShared>();
            if (bankAccountSystem.TryGetSalaryJobEntry(_jobs[args.Id], EconomyBankAccountSystemShared.DefaultSalariesPrototypeId, out var jobEntry))
                SalaryAmountBox.Value = (int)jobEntry.Value.Sallary;
        };
        ChangeSalaryInfoButton.OnPressed += _ =>
        {
            if (_currentAccountId is null || !TryGetCurrentAccount(out var account))
                return;

            var jobName = account.JobName;
            var salary = account.Salary;
            var selectedJob = _jobs[JobPresetOptionButton.SelectedId];
            if (JobPresetOptionButton.SelectedId != _jobs.IndexOf(jobName.GetValueOrDefault()))
                OnChangeJob?.Invoke(_currentAccountId, selectedJob);
            if (SalaryAmountBox.Value != (int)salary.GetValueOrDefault())
                OnChangeSalary?.Invoke(_currentAccountId, (ulong)SalaryAmountBox.Value);
        };
    }

    public void ApplyConfiguration(ProtoId<JobPrototype>? defaultJob,
                                   IReadOnlyList<int>? salaryButtons,
                                   EconomyBankAccountMask accountMask,
                                   IReadOnlyList<BankAccountTag>? accountTags,
                                   bool allowCentralAccounts,
                                   bool allowRestrictedAccounts)
    {
        _accountMask = accountMask;
        _accountTags = accountTags is { Count: > 0 } tags ? new List<BankAccountTag>(tags) : null;
        _allowCentralAccounts = allowCentralAccounts;
        _allowRestrictedAccounts = allowRestrictedAccounts;

        SetDefaultJob(defaultJob);
        ConfigureSalaryButtons(salaryButtons);

        if (TryGetCurrentAccount(out var account))
            UpdateJobPreset(account, account.JobName);
        else
            UpdateJobPreset(null, null);
    }

    public void UpdateAccountList()
    {
        AccountList.Clear();
        var accounts = _bankAccountSystem.GetAccounts(_accountMask, _accountTags);
        _accounts.Clear();
        foreach (var (_, account) in accounts)
        {
            if (!IsAccountAllowed(account.Comp))
                continue;

            _accounts.Add(new AccountEntry(account.Comp.AccountID, FormFieldName(account.Comp)));
        }

        FillList();
    }

    public void OnUpdateState(string? accountID,
                              string? accountName,
                              ulong? balance,
                              ulong? penalty,
                              bool? blocked,
                              bool? canReachPayDay,
                              string? jobName,
                              ulong? salary,
                              ulong? payrollSalary,
                              bool? payrollCanReach)
    {
        if (accountID is null || _currentAccountId != accountID)
        {
            ClearCurrentAccount();
            return;
        }

        var lookupAccountId = accountID;
        AccountIdLabel.Text = accountID;
        AccountOwnerLabel.Text = accountName ?? "-";
        var accountBalance = balance is not null ? string.Format("{0:N0}", balance) : "-";
        AccountBalanceLabel.Text = accountBalance;
        var accountBlocked = blocked is not null ? (blocked.Value ? Loc.GetString("economybanksystem-management-console-management-block") : Loc.GetString("economybanksystem-management-console-management-unblock"))
                                          : "-";
        AccountBlockedLabel.Text = accountBlocked;
        EconomyBankAccountComponent? accountComp = null;
        if (lookupAccountId != null && _bankAccountSystem.TryGetAccount(lookupAccountId, out var foundAccount))
            accountComp = foundAccount.Value.Comp;

        var accountSalary = salary ?? 0;
        var displaySalary = payrollSalary ?? accountSalary;
        var displayReachable = payrollCanReach ?? canReachPayDay;
        AccountPaydayStatusLabel.Text = displayReachable is not null ? (displayReachable.Value ? Loc.GetString("economybanksystem-management-console-management-salary-reachable", ("salary", displaySalary)) : Loc.GetString("economybanksystem-management-console-management-salary-not-reachable", ("salary", displaySalary)))
                                                      : "-";
        var blockedButton = blocked is not null ? (blocked.Value ? Loc.GetString("economybanksystem-management-console-management-unblock-button") : Loc.GetString("economybanksystem-management-console-management-block-button"))
                                                : "-";
        BlockButton.Text = blockedButton;
        var salaryValue = accountComp is not null && IsReadOnlyAccount(accountComp) ? displaySalary : accountSalary;
        SalaryAmountBox.Value = (int) salaryValue;

        UpdateJobPreset(accountComp, jobName);
        UpdateButtons(Priveleged);
    }

    private void OnSelectAccount(ItemList.Item accountId)
    {
        if (accountId.Metadata is not string account)
            return;

        _currentAccountId = account;
        if (!TryGetCurrentAccount(out var accountComp))
        {
            ClearCurrentAccount();
            return;
        }

        FillAccountInfo(accountComp);
        UpdateButtons(Priveleged);
    }

    private void OnSalaryValueChanged(ValueChangedEventArgs args)
    {
        // what shitcode does to a man
        SalaryAmountBox.ValueChanged -= OnSalaryValueChanged;
        SalaryAmountBox.Value = Math.Max(0, args.Value);
        SalaryAmountBox.ValueChanged += OnSalaryValueChanged;
    }

    private void OnTextEnteredAccount(LineEdit.LineEditEventArgs eventArgs)
    {
        AccountList.Clear();
        var search = eventArgs.Text;
        foreach (var entry in _accounts)
        {
            if (entry.DisplayName.Contains(search, StringComparison.CurrentCultureIgnoreCase))
            {
                var field = AccountList.AddItem(entry.DisplayName);
                field.Metadata = entry.AccountId;
                field.OnSelected += OnSelectAccount;
            }
        }
        if (AccountList.Count == 0)
        {
            AccountList.AddItem("No data acquired");
            return;
        }
        AccountList.SortItemsByText();
    }

    private void FillList()
    {
        foreach (var entry in _accounts)
        {
            var field = AccountList.AddItem(entry.DisplayName);
            field.Metadata = entry.AccountId;
            field.OnSelected += OnSelectAccount;
        }

        AccountList.SortItemsByText();
    }

    private string FormFieldName(EconomyBankAccountComponent account)
    {
        return account.AccountID + " - " + account.AccountName;
    }

    private bool IsReadOnlyAccount(EconomyBankAccountComponent account)
    {
        if (_bankAccountSystem.IsCentralCommandAccount(account.AccountID))
            return true;

        return _bankAccountSystem.IsRestrictedDepartmentAccount(account);
    }

    private string GetRestrictedJobText(EconomyBankAccountComponent account)
    {
        var key = _bankAccountSystem.IsDepartmentCashAccount(account)
            ? "economybanksystem-management-console-management-job-placeholder-cash"
            : "economybanksystem-management-console-management-job-placeholder-department";
        return Loc.GetString(key);
    }

    private void UpdateJobPreset(EconomyBankAccountComponent? account, string? jobName)
    {
        if (_defaultJobIndex >= 0)
            JobPresetOptionButton.SetItemText(_defaultJobIndex, _defaultJobName);

        if (account != null && IsReadOnlyAccount(account))
        {
            if (_defaultJobIndex >= 0)
            {
                JobPresetOptionButton.SetItemText(_defaultJobIndex, GetRestrictedJobText(account));
                JobPresetOptionButton.SelectId(_defaultJobIndex);
            }
            return;
        }

        JobPresetOptionButton.SelectId(GetJobIndex(jobName));
    }

    private int GetJobIndex(string? jobName)
    {
        if (jobName is not null)
        {
            var jobIndex = _jobs.IndexOf(jobName);
            if (jobIndex >= 0)
                return jobIndex;
        }

        var defaultIndex = _jobs.IndexOf(_defaultJob);
        if (defaultIndex >= 0)
            return defaultIndex;

        return _jobs.Count > 0 ? 0 : -1;
    }

    private void UpdateButtons(bool priveleged)
    {
        var disabled = _currentAccountId is null || !priveleged;
        var readOnly = TryGetCurrentAccount(out var account) && IsReadOnlyAccount(account);

        BlockButton.Disabled = disabled;
        ChangeNameButton.Disabled = disabled || readOnly;
        JobPresetOptionButton.Disabled = disabled || readOnly;
        SalaryAmountBox.LineEditDisabled = disabled || readOnly;
        SalaryAmountBox.SetButtonDisabled(disabled || readOnly);
        ChangeSalaryInfoButton.Disabled = disabled || readOnly;
    }

    private void ClearCurrentAccount()
    {
        AccountIdLabel.Text = "-";
        AccountOwnerLabel.Text = "-";
        AccountBalanceLabel.Text = "-";
        AccountBlockedLabel.Text = "-";
        AccountPaydayStatusLabel.Text = "-";
        BlockButton.Text = "-";
        SalaryAmountBox.Value = 0;

        _currentAccountId = null;
        UpdateJobPreset(null, null);
        UpdateButtons(Priveleged);
    }

    private void FillAccountInfo(EconomyBankAccountComponent account)
    {
        AccountIdLabel.Text = account.AccountID;
        AccountOwnerLabel.Text = account.AccountName;
        var balance = account.Balance;
        AccountBalanceLabel.Text = balance.ToString("N0") ?? "-";
        AccountBlockedLabel.Text = account.Blocked ? Loc.GetString("economybanksystem-management-console-management-block") :
                                                     Loc.GetString("economybanksystem-management-console-management-unblock");
        var salary = account.Salary ?? 0;
        var reachable = account.CanReachPayDay;
        var readOnly = IsReadOnlyAccount(account);
        if (readOnly && _bankAccountSystem.TryGetAssignedPayroll(account, out var payroll, out var payrollCanReach))
        {
            salary = payroll;
            reachable = payrollCanReach;
        }
        AccountPaydayStatusLabel.Text = reachable
            ? Loc.GetString("economybanksystem-management-console-management-salary-reachable", ("salary", salary))
            : Loc.GetString("economybanksystem-management-console-management-salary-not-reachable", ("salary", salary));
        BlockButton.Text = account.Blocked ? Loc.GetString("economybanksystem-management-console-management-unblock-button") :
                                             Loc.GetString("economybanksystem-management-console-management-block-button");
        UpdateJobPreset(account, account.JobName);
        SalaryAmountBox.Value = (int) salary;
    }

    private void SetDefaultJob(ProtoId<JobPrototype>? job)
    {
        _defaultJob = job ?? DefaultJobPrototype;
        if (_prototypeManager.TryIndex(_defaultJob, out var defaultJobPrototype))
            _defaultJobName = Loc.GetString(defaultJobPrototype.Name);
        else
            _defaultJobName = _defaultJob;

        UpdateDefaultJobIndex();
    }

    private void UpdateDefaultJobIndex()
    {
        _defaultJobIndex = GetJobIndex(null);
        if (_defaultJobIndex < 0 && _jobs.Count > 0)
            _defaultJobIndex = 0;
    }

    private void ConfigureSalaryButtons(IReadOnlyList<int>? buttonSteps)
    {
        var source = buttonSteps is { Count: > 0 } steps ? steps : DefaultSalaryButtons;
        var leftButtons = new List<int>();
        var rightButtons = new List<int>();

        foreach (var value in source)
        {
            if (value < 0)
                leftButtons.Add(value);
            else if (value > 0)
                rightButtons.Add(value);
        }

        if (leftButtons.Count == 0 && rightButtons.Count == 0)
        {
            foreach (var value in DefaultSalaryButtons)
            {
                if (value < 0)
                    leftButtons.Add(value);
                else if (value > 0)
                    rightButtons.Add(value);
            }
        }

        SalaryAmountBox.SetButtons(leftButtons, rightButtons);
        SalaryAmountBox.SetButtonDisabled(true);
    }

    private bool TryGetCurrentAccount([NotNullWhen(true)] out EconomyBankAccountComponent? account)
    {
        account = null;
        if (_currentAccountId is null)
            return false;

        if (!_bankAccountSystem.TryGetAccount(_currentAccountId, out var foundAccount))
            return false;

        account = foundAccount.Value.Comp;
        return true;
    }

    private readonly record struct AccountEntry(string AccountId, string DisplayName);

    private bool IsAccountAllowed(EconomyBankAccountComponent account)
    {
        if (!_allowCentralAccounts && _bankAccountSystem.IsCentralCommandAccount(account.AccountID))
            return false;

        if (!_allowRestrictedAccounts && _bankAccountSystem.IsRestrictedDepartmentAccount(account))
            return false;

        return _accountMask switch
        {
            EconomyBankAccountMask.All => true,
            EconomyBankAccountMask.NotBlocked => !account.Blocked,
            EconomyBankAccountMask.Blocked => account.Blocked,
            EconomyBankAccountMask.ByTags => _accountTags != null && account.AccountTags.Any(_accountTags.Contains),
            _ => true
        };
    }
}
