using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Content.Shared._Invicta.Economy.Bank;
using Robust.Shared.Prototypes;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Shared.Roles;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Invicta.Economy.Bank.UI.ManagementConsole.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccountHolderTab : Control
{
    private string? _currentAccountId;

    [Dependency] private readonly EntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly List<string> _jobs = new();
    private static readonly ProtoId<JobPrototype> DefaultJobPrototype = "Passenger";
    private static readonly int[] DefaultSalaryButtons = { -10, -1, 1, 10 };
    private ProtoId<JobPrototype> _defaultJob = DefaultJobPrototype;
    private EconomyBankAccountSystemShared _bankAccountSystem = default!;
    private string _defaultJobName = string.Empty;
    private int _defaultJobIndex = -1;
    private EconomyBankAccountMask _accountMask = EconomyBankAccountMask.All;
    private List<BankAccountTag>? _accountTags;
    private bool _allowCentralAccounts;
    private bool _allowRestrictedAccounts;

    public Entity<EconomyAccountHolderComponent>? CurrentCard;
    public bool Priveleged;

    public Action<string, string>? OnChangeNamePressed;
    public Action<string, bool>? OnBlockAccountPressed;
    public Action<string, string>? OnChangeJob;
    public Action<string, ulong>? OnChangeSalary;
    public Action<NetEntity, string>? OnChangeAccountPressed;
    public Action<NetEntity>? OnInitializeAccountPressed;

    public AccountHolderTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _bankAccountSystem = _entityManager.System<EconomyBankAccountSystemShared>();
        SetDefaultJob(null);

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>().ToList();
        jobs.Sort((x, y) => string.Compare(x.LocalizedName, y.LocalizedName, StringComparison.CurrentCulture));
        foreach (var job in jobs)
        {
            if (!job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                continue;

            _jobs.Add(job.ID);
            JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobs.Count - 1);
        }

        UpdateDefaultJobIndex();
        ConfigureSalaryButtons(null);

        GetAccount(CurrentCard);

        SalaryAmountBox.ValueChanged += OnSalaryValueChanged;

        ChangeNameButton.OnPressed += _ =>
        {
            if (_currentAccountId is null)
                return;

            OnChangeNamePressed?.Invoke(_currentAccountId, ChangeNamePrompt.Text);
        };
        BlockButton.OnPressed += _ =>
        {
            if (_currentAccountId is null)
                return;

            var blocked = TryGetCurrentAccount(out var account) && account.Blocked;
            OnBlockAccountPressed?.Invoke(_currentAccountId, !blocked);
        };
        JobPresetOptionButton.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);

            var bankAccountSystem = _entityManager.System<EconomyBankAccountSystemShared>();
            if (bankAccountSystem.TryGetSalaryJobEntry(_jobs[args.Id], EconomyBankAccountSystemShared.DefaultSalariesPrototypeId, out var jobEntry))
                SalaryAmountBox.Value = (int)jobEntry.Value.Sallary;
        };
        ChangeSalaryInfoButton.OnPressed += _ =>
        {
            if (_currentAccountId is null || !TryGetCurrentAccount(out var account))
                return;

            var jobName = account.JobName;
            var salary = account.Salary;
            var selectedJob = _jobs[JobPresetOptionButton.SelectedId];
            if (JobPresetOptionButton.SelectedId != _jobs.IndexOf(jobName.GetValueOrDefault()))
                OnChangeJob?.Invoke(_currentAccountId, selectedJob);
            if (SalaryAmountBox.Value != (int)salary.GetValueOrDefault())
                OnChangeSalary?.Invoke(_currentAccountId, (ulong)SalaryAmountBox.Value);
        };
        ChangeAccountButton.OnPressed += _ =>
        {
            if (CurrentCard is null)
                return;

            if (!_bankAccountSystem.TryGetAccount(ChangeAccountPrompt.Text, out var targetAccount))
            {
                ErrorLabel.Text = Loc.GetString("economybanksystem-management-console-error-invalid-account");
                return;
            }

            if (!IsAccountAllowed(targetAccount.Value.Comp))
            {
                ErrorLabel.Text = Loc.GetString("economybanksystem-management-console-error-protected-account");
                return;
            }

            ErrorLabel.Text = string.Empty;
            var netEntity = _entityManager.GetNetEntity(CurrentCard.Value);
            OnChangeAccountPressed?.Invoke(netEntity, ChangeAccountPrompt.Text);
        };
        InitializeAccountButton.OnPressed += _ =>
        {
            if (CurrentCard is null)
                return;

            var netEntity = _entityManager.GetNetEntity(CurrentCard.Value);
            OnInitializeAccountPressed?.Invoke(netEntity);
        };
    }

    public void ApplyConfiguration(ProtoId<JobPrototype>? defaultJob,
                                   IReadOnlyList<int>? salaryButtons,
                                   EconomyBankAccountMask accountMask,
                                   IReadOnlyList<BankAccountTag>? accountTags,
                                   bool allowCentralAccounts,
                                   bool allowRestrictedAccounts)
    {
        _accountMask = accountMask;
        _accountTags = accountTags is { Count: > 0 } tags ? new List<BankAccountTag>(tags) : null;
        _allowCentralAccounts = allowCentralAccounts;
        _allowRestrictedAccounts = allowRestrictedAccounts;

        SetDefaultJob(defaultJob);
        ConfigureSalaryButtons(salaryButtons);

        if (TryGetCurrentAccount(out var account))
            UpdateJobPreset(account, account.JobName);
        else
            UpdateJobPreset(null, null);
    }

    private void GetAccount(EconomyAccountHolderComponent? accountHolder)
    {
        if (accountHolder is not null && _bankAccountSystem.TryGetAccount(accountHolder.AccountID, out var accountEnt))
        {
            _currentAccountId = accountEnt.Value.Comp.AccountID;
            FillAccount(accountEnt.Value.Comp);
            UpdateButtons(Priveleged);
            return;
        }

        _currentAccountId = null;
        FillAccount(null);
        UpdateButtons(Priveleged);
    }

    private void FillAccount(EconomyBankAccountComponent? account)
    {
        AccountInitLabel.Text = account is not null ? Loc.GetString("economybanksystem-management-console-management-initialized") :
                                                      Loc.GetString("economybanksystem-management-console-management-not-initialized");
        AccountIdLabel.Text = account is not null ? account.AccountID : "-";
        AccountOwnerLabel.Text = account is not null ? account.AccountName : "-";
        var balance = account is not null ? string.Format("{0:N0}", account.Balance) : "-";
        AccountBalanceLabel.Text = balance;
        var blocked = account is not null ? (account.Blocked ? Loc.GetString("economybanksystem-management-console-management-block") : Loc.GetString("economybanksystem-management-console-management-unblock"))
                                          : "-";
        var blockedButton = account is not null ? (account.Blocked ? Loc.GetString("economybanksystem-management-console-management-unblock-button") : Loc.GetString("economybanksystem-management-console-management-block-button"))
                                                : "-";
        AccountBlockStatusLabel.Text = blocked;
        BlockButton.Text = blockedButton;
        var salary = account?.Salary ?? 0;
        var paydayStatus = account is not null ? (account.CanReachPayDay ? Loc.GetString("economybanksystem-management-console-management-salary-reachable", ("salary", salary)) : Loc.GetString("economybanksystem-management-console-management-salary-not-reachable", ("salary", salary)))
                                               : "-";
        AccountPaydayStatusLabel.Text = paydayStatus;
        UpdateJobPreset(account, account?.JobName);
        SalaryAmountBox.Value = (int)salary;
    }

    private void UpdateButtons(bool priveleged)
    {
        var noAccount = !priveleged || _currentAccountId is null;
        var readOnly = TryGetCurrentAccount(out var account) && IsReadOnlyAccount(account);

        ChangeNameButton.Disabled = noAccount || readOnly;
        BlockButton.Disabled = noAccount;
        ChangeAccountButton.Disabled = !priveleged || CurrentCard is null || readOnly;
        InitializeAccountButton.Disabled = !priveleged || _currentAccountId is not null || CurrentCard is null;
        JobPresetOptionButton.Disabled = noAccount || readOnly;
        SalaryAmountBox.LineEditDisabled = noAccount || readOnly;
        SalaryAmountBox.SetButtonDisabled(noAccount || readOnly);
        ChangeSalaryInfoButton.Disabled = noAccount || readOnly;
    }

    private void OnSalaryValueChanged(ValueChangedEventArgs args)
    {
        // what shitcode does to a man
        SalaryAmountBox.ValueChanged -= OnSalaryValueChanged;
        SalaryAmountBox.Value = Math.Max(0, args.Value);
        SalaryAmountBox.ValueChanged += OnSalaryValueChanged;
    }

    private bool IsReadOnlyAccount(EconomyBankAccountComponent account)
    {
        if (_bankAccountSystem.IsCentralCommandAccount(account.AccountID))
            return true;

        return _bankAccountSystem.IsRestrictedDepartmentAccount(account);
    }

    private string GetRestrictedJobText(EconomyBankAccountComponent account)
    {
        var key = _bankAccountSystem.IsDepartmentCashAccount(account)
            ? "economybanksystem-management-console-management-job-placeholder-cash"
            : "economybanksystem-management-console-management-job-placeholder-department";
        return Loc.GetString(key);
    }

    private void UpdateJobPreset(EconomyBankAccountComponent? account, string? jobName)
    {
        if (_defaultJobIndex >= 0)
            JobPresetOptionButton.SetItemText(_defaultJobIndex, _defaultJobName);

        if (account != null && IsReadOnlyAccount(account))
        {
            if (_defaultJobIndex >= 0)
            {
                JobPresetOptionButton.SetItemText(_defaultJobIndex, GetRestrictedJobText(account));
                JobPresetOptionButton.SelectId(_defaultJobIndex);
            }
            return;
        }

        JobPresetOptionButton.SelectId(GetJobIndex(jobName));
    }

    private int GetJobIndex(string? jobName)
    {
        if (jobName is not null)
        {
            var jobIndex = _jobs.IndexOf(jobName);
            if (jobIndex >= 0)
                return jobIndex;
        }

        var defaultIndex = _jobs.IndexOf(_defaultJob);
        if (defaultIndex >= 0)
            return defaultIndex;

        return _jobs.Count > 0 ? 0 : -1;
    }

    public void OnUpdateState(string? holderID,
                              string? accountID,
                              string? accountName,
                              ulong? balance,
                              ulong? penalty,
                              bool? blocked,
                              bool? canReachPayDay,
                              string? jobName,
                              ulong? salary,
                              ulong? payrollSalary,
                              bool? payrollCanReach)
    {
        if (CurrentCard is null || holderID is null)
        {
            _currentAccountId = null;
            FillAccount(null);
            UpdateButtons(Priveleged);
            return;
        }

        if (accountID is null || holderID != accountID)
        {
            RefreshCurrentAccountDisplay();
            UpdateButtons(Priveleged);
            return;
        }

        _currentAccountId = accountID;

        var lookupAccountId = accountID;
        AccountInitLabel.Text = accountID is not null ? Loc.GetString("economybanksystem-management-console-management-initialized") :
                                                      Loc.GetString("economybanksystem-management-console-management-not-initialized");
        accountID ??= "-";
        AccountIdLabel.Text = accountID;
        AccountOwnerLabel.Text = accountName ?? "-";
        var accountBalance = balance is not null ? string.Format("{0:N0}", balance) : "-";
        AccountBalanceLabel.Text = accountBalance;
        var accountBlocked = blocked is not null ? (blocked.Value ? Loc.GetString("economybanksystem-management-console-management-block") : Loc.GetString("economybanksystem-management-console-management-unblock"))
                                          : "-";
        var blockedButton = blocked is not null ? (blocked.Value ? Loc.GetString("economybanksystem-management-console-management-unblock-button") : Loc.GetString("economybanksystem-management-console-management-block-button"))
                                                : "-";
        AccountBlockStatusLabel.Text = accountBlocked;
        BlockButton.Text = blockedButton;
        EconomyBankAccountComponent? accountComp = null;
        if (lookupAccountId != null && _bankAccountSystem.TryGetAccount(lookupAccountId, out var foundAccount))
            accountComp = foundAccount.Value.Comp;

        var accountSalary = salary ?? 0;
        var displaySalary = payrollSalary ?? accountSalary;
        var displayReachable = payrollCanReach ?? canReachPayDay;
        var paydayStatus = displayReachable is not null ? (displayReachable.Value ? Loc.GetString("economybanksystem-management-console-management-salary-reachable", ("salary", displaySalary)) : Loc.GetString("economybanksystem-management-console-management-salary-not-reachable", ("salary", displaySalary)))
                                                      : "-";
        AccountPaydayStatusLabel.Text = paydayStatus;
        var salaryValue = accountComp is not null && IsReadOnlyAccount(accountComp) ? displaySalary : accountSalary;
        SalaryAmountBox.Value = (int) salaryValue;

        UpdateJobPreset(accountComp, jobName);
        UpdateButtons(Priveleged);
    }

    private void SetDefaultJob(ProtoId<JobPrototype>? job)
    {
        _defaultJob = job ?? DefaultJobPrototype;
        if (_prototypeManager.TryIndex(_defaultJob, out var defaultJobPrototype))
            _defaultJobName = Loc.GetString(defaultJobPrototype.Name);
        else
            _defaultJobName = _defaultJob;

        UpdateDefaultJobIndex();
    }

    private void UpdateDefaultJobIndex()
    {
        _defaultJobIndex = GetJobIndex(null);
        if (_defaultJobIndex < 0 && _jobs.Count > 0)
            _defaultJobIndex = 0;
    }

    private void ConfigureSalaryButtons(IReadOnlyList<int>? buttonSteps)
    {
        var source = buttonSteps is { Count: > 0 } steps ? steps : DefaultSalaryButtons;
        var leftButtons = new List<int>();
        var rightButtons = new List<int>();

        foreach (var value in source)
        {
            if (value < 0)
                leftButtons.Add(value);
            else if (value > 0)
                rightButtons.Add(value);
        }

        if (leftButtons.Count == 0 && rightButtons.Count == 0)
        {
            foreach (var value in DefaultSalaryButtons)
            {
                if (value < 0)
                    leftButtons.Add(value);
                else if (value > 0)
                    rightButtons.Add(value);
            }
        }

        SalaryAmountBox.SetButtons(leftButtons, rightButtons);
        SalaryAmountBox.SetButtonDisabled(true);
    }

    private void RefreshCurrentAccountDisplay()
    {
        if (_currentAccountId is null)
        {
            FillAccount(null);
            return;
        }

        if (_bankAccountSystem.TryGetAccount(_currentAccountId, out var account))
        {
            FillAccount(account.Value.Comp);
            return;
        }

        _currentAccountId = null;
        FillAccount(null);
    }

    private bool TryGetCurrentAccount([NotNullWhen(true)] out EconomyBankAccountComponent? account)
    {
        account = null;
        if (_currentAccountId is null)
            return false;

        if (!_bankAccountSystem.TryGetAccount(_currentAccountId, out var foundAccount))
            return false;

        account = foundAccount.Value.Comp;
        return true;
    }

    private bool IsAccountAllowed(EconomyBankAccountComponent account)
    {
        if (!_allowCentralAccounts && _bankAccountSystem.IsCentralCommandAccount(account.AccountID))
            return false;

        if (!_allowRestrictedAccounts && _bankAccountSystem.IsRestrictedDepartmentAccount(account))
            return false;

        return _accountMask switch
        {
            EconomyBankAccountMask.All => true,
            EconomyBankAccountMask.NotBlocked => !account.Blocked,
            EconomyBankAccountMask.Blocked => account.Blocked,
            EconomyBankAccountMask.ByTags => _accountTags != null && account.AccountTags.Any(_accountTags.Contains),
            _ => true
        };
    }
}
