using System.Linq;
using Content.Client.UserInterface;
using Content.Shared.Ame.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Invicta.Skills
{
    [GenerateTypedNameReferences]
    public sealed partial class SkillsWindow : DefaultWindow
    {
        public SkillsWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        public void UpdateState(BoundUserInterfaceState state)
        {
        }
    }
}
